const assert=require('node:assert/strict');
const C=require('../civic-core.js'),D=require('../civic-data.js');
const balanced=C.projectBudget({});
assert.equal(balanced.capital,8500000);
assert.equal(balanced.fullUpkeep,670000);
assert.deepEqual(balanced.rows.map(r=>r.operating),[670000,690100,710803,732127,754091]);
assert.deepEqual(balanced.rows.map(r=>r.balance),[2830000,3139900,3429097,3696970,3942879]);
const storm=C.projectBudget({event:'storm'});
assert.equal(storm.totalRepair,3063000);
assert.equal(storm.finalBalance,879879);
assert.equal(storm.firstShortfall,null);
assert.equal(C.projectBudget({preset:'community',event:'storm'}).firstShortfall,3);
assert.equal(C.projectBudget({preset:'resilient',event:'storm'}).totalRepair,1750000);
const recovered=C.projectBudget({plan:[4000,5000,2750,0,0],upkeep:50});
assert.equal(recovered.firstShortfall,1,'An early funding gap must not disappear when later top-ups restore a positive balance');
assert.equal(recovered.fundingGap,197500);
assert.ok(recovered.finalBalance>0);
const noMaintenance=C.projectBudget({upkeep:0,event:'storm'});
assert.equal(noMaintenance.rows[2].condition,70);
assert.equal(noMaintenance.rows[4].condition,40);
assert.equal(noMaintenance.totalOperating,0);
assert.equal(noMaintenance.totalRepair,3644000);
assert.ok(noMaintenance.totalRepair>storm.totalRepair,'Skipping upkeep must worsen the modeled storm cost at the same investment levels');
for(const preset of Object.keys(D.presets))for(const upkeep of [0,25,50,75,100])for(const event of ['none','storm']){
  const r=C.projectBudget({preset,upkeep,event});
  assert.equal(r.finalBalance+r.totalCost,16000000,'Every dollar of funding must be accounted for exactly once');
  let cash=0;
  r.rows.forEach(y=>{cash+=y.funding-y.capital-y.operating-y.repair;assert.equal(cash,y.balance);assert.ok(y.operating<=y.required);assert.ok(Number.isInteger(y.balance));});
  if(event==='none')assert.equal(r.totalRepair,0);
  if(upkeep===100)assert.ok(r.rows.every(y=>y.condition===100));
  assert.equal(r.fundingGap,Math.max(0,-Math.min(...r.rows.map(y=>y.balance))));
}
for(const bad of ['__proto__','constructor','toString','<script>'])assert.deepEqual(C.fromParams(new URLSearchParams('preset='+encodeURIComponent(bad))),C.budgetSettings());
assert.deepEqual(C.fromParams(new URLSearchParams('plan=-250,Infinity,123,99999,&upkeep=17&event=x')).plan,D.presets.balanced.plan);
const valid={plan:[0,5000,250,4000,3000],upkeep:25,event:'storm'};
assert.deepEqual(C.fromParams(new URLSearchParams(C.budgetValues(valid))),valid);
const snapshot=C.budgetSettings(valid);valid.plan[0]=1000;assert.equal(snapshot.plan[0],0,'Saving a comparison must copy the allocation array');
const note=C.budgetNote(storm.settings,snapshot,'I chose readiness because…','https://example.test/fieldwork/?demo=budget');
assert.ok(note.includes('$879,879'));assert.ok(note.includes('## My reasoning'));assert.ok(!note.includes('undefined'));assert.ok(!note.includes('\\n'));
const ids=new Set(D.exhibits.map(e=>e.id));assert.equal(ids.size,9);
for(const w of D.witnesses)assert.ok(w.knows.every(id=>ids.has(id)));
for(const f of D.findings)assert.ok(f.evidence.every(id=>ids.has(id)));
assert.deepEqual(C.hearingSettings(new URLSearchParams('exhibit=bogus&witness=__proto__')),{exhibit:'E09',witness:'director'});
const hearing=C.hearingNote({pins:['E03','E06'],witness:'engineer',questions:[{witness:'engineer',text:'Was the wet-flow test complete?',evidence:['E06']}],findings:{accepted:'contradicted',maintenance:'supported',cause:'unresolved'},conclusion:'The supplied file leaves the cause open.'},'https://example.test/?demo=hearing','https://example.test/');
assert.ok(hearing.includes('To Jonah Reed: Was the wet-flow test complete? [E06]'));
assert.ok(hearing.includes('AI-generated'));assert.ok(hearing.includes('My assessment: unresolved'));assert.ok(hearing.includes('https://example.test/lessons/hearing-case.md'));
console.log('Passed: independent five-year budget fixtures; 30 funding-conservation scenarios; early shortfall recovery; storm/upkeep behavior; malformed URLs; copied comparisons; and both Markdown handoffs.');
