const assert=require('node:assert/strict');
const J=require('../journey-core.js');
const base='http://127.0.0.1:4173/portfolio/?demo=budget&plan=1000#old';

const s=J.blank();
s.visited=['reach','instruments','missing'];
s.step='missing';s.case='alaska1964';
s.text.reach='The tsunami goes far?';
s.text.gapOcean='We would know about shaking,\nbut not the actual water response.';
s.hints=['water','gap-ocean'];s.reviewedGaps=['ocean'];
assert.equal(J.choose(s,'water','ground'),true);
assert.equal(J.result(s,'water').correct,false);
assert.equal(J.choose(s,'water','water'),true);
assert.equal(J.result(s,'water').correct,true);
assert.equal(J.choose(s,'alerts','unknown'),false);
let note=J.checkpoint(s,base);
assert.ok(note.includes('Current stop: missing'));
assert.ok(note.includes('No maintenance answer supplied; do not infer a learner choice'));
assert.ok(!note.includes('Maintenance example: Keep equipment powered'));
assert.ok(note.includes(s.text.gapOcean));
assert.ok(note.includes('Attempts: 2; hint used: yes.'));
assert.ok(note.includes('Who evaluates the tsunami threat and issues U.S. tsunami alerts?'));
assert.ok(note.includes('Not attempted.'));
assert.ok(note.includes('navigation only, not proof of learning'));
assert.ok(note.includes('could still use seismic information'));
assert.ok(note.includes('step=readiness'));
assert.ok(note.includes('Not tried. Displayed defaults are not a learner answer.'));
assert.equal(J.travelNote(s,base),null);
const initialTravel=J.travelEstimate(2000,3000);
assert.ok(Math.abs(initialTravel.speedKmH-504.3)<1);
assert.ok(Math.abs(initialTravel.hours-5.95)<0.1);
assert.ok(J.travelEstimate(6000,3000).hours<initialTravel.hours);
assert.ok(J.travelEstimate(2000,4000).hours>initialTravel.hours);
s.travel={depth:4000,distance:3000,adjusted:true};
s.text.travelInsight='Deeper water shortened the crossing time.';
note=J.checkpoint(s,base);
assert.ok(note.includes('Learner-selected parameters: 3000 km of open ocean at a constant depth of 4000 m.'));
assert.ok(note.includes('Learner\'s interpretation: Deeper water shortened the crossing time.'));
assert.ok(note.includes('not a measurement of the selected historical event'));
const crossing=J.travelNote(s,base);
assert.ok(crossing.includes('My selected distance: 3000 km.'));
assert.ok(crossing.includes('My selected constant ocean depth: 4000 m.'));
assert.ok(crossing.includes('What I noticed: Deeper water shortened the crossing time.'));
assert.ok(crossing.includes('step=reach'));
assert.ok(!crossing.includes('## Fixed checks'));
assert.ok(!note.includes('undefined')&&!note.includes('plan='));
assert.equal(new URL(J.url(base,s)).pathname,'/portfolio/');
assert.equal(new URL(J.url(base,s)).searchParams.get('case'),'alaska1964');
assert.equal(new URL(J.url(base,s)).hash,'');

s.text.maintenancePower='Keep sensors powered.';
s.text.maintenancePeople='Prepare accessible evacuation plans.';
s.job='people';note=J.checkpoint(s,base);
assert.ok(note.includes('My maintenance explanation: Prepare accessible evacuation plans.'));
assert.ok(!note.includes('My maintenance explanation: Keep sensors powered.'));
s.case='japan2011';s.step='explain';
s.text.explanation='Waves can cross the Pacific. Observations, alerts, and practical routes all matter. Maintenance keeps those functions ready; an alert cannot guarantee everyone can evacuate.';
for(const id of ['water','alerts','action','budget','transfer','quiet'])J.choose(s,id,J.checks[id].correct);
note=J.checkpoint(s,base,'final');
assert.ok(note.includes(s.text.explanation));
assert.ok(note.includes('Active historical example: Japan · 2011'));
assert.ok(note.includes('Combined earthquake and tsunami'));
assert.ok(note.includes('step=review'));
assert.ok(note.includes('contains no live earthquake snapshot'));
s.step='review';s.text.review='I remember the difference between ground and water measurements.';
note=J.checkpoint(s,base,'review');
assert.ok(note.includes('Discuss my return-visit answer'));
assert.ok(note.includes('step=explain'));

assert.deepEqual(J.normalize({version:'old',text:{reach:'stale'}}),J.blank());
const dirty=J.normalize({...s,case:'invented',step:'mastered',hints:['injected','water','water'],visited:['passed','reach'],text:{reach:'x'.repeat(9000),secret:'not allowed'},choices:{alerts:'injected'},attempts:{water:Array(20).fill('water')}});
assert.equal(dirty.case,'alaska1964');assert.equal(dirty.step,'reach');
assert.equal(dirty.text.reach.length,1200);assert.equal(dirty.text.secret,undefined);
assert.deepEqual(dirty.hints,['water']);assert.deepEqual(dirty.visited,['reach']);
assert.equal(dirty.choices.alerts,undefined);assert.equal(dirty.attempts.water.length,8);
assert.deepEqual(J.normalize({...s,travel:{depth:99999,distance:-12,adjusted:true}}).travel,{depth:6000,distance:500,adjusted:true});
assert.equal(J.entry(s,new URLSearchParams('demo=budget&case=alaska1964&step=reach')).case,'japan2011');
assert.equal(J.entry(s,new URLSearchParams('demo=quakes&case=alaska1964&step=missing')).step,'missing');
assert.equal(J.entry(s,new URLSearchParams('demo=quakes&step=unknown')).step,'review');
console.log('Journey: state boundaries, corrections, scoped notes, checkpoints, deep links, and return visit passed.');
