const assert=require('node:assert/strict');
const fs=require('node:fs');
const R=require('../../chrome-extension/routing.js');
const E=require('../entry.js');
const base='https://denson.github.io/fieldwork/';
const portfolioHtml=fs.readFileSync(require.resolve('../index.html'),'utf8');
assert.match(portfolioHtml,/href="https:\/\/box\.boodle\.ai\/a\/@EarthquakeTsunamiGuide" data-fieldwork-open-guide/);
assert.match(portfolioHtml,/class="experience quake-card" href="tsunami\.html" data-fieldwork-combo/);
const tsunamiHtml=fs.readFileSync(require.resolve('../tsunami.html'),'utf8');
assert.match(tsunamiHtml,/id="tsunami-journey"/);
assert.match(tsunamiHtml,/href="https:\/\/box\.boodle\.ai\/a\/@EarthquakeTsunamiGuide" data-fieldwork-open-guide/);
assert.doesNotMatch(tsunamiHtml,/id="budget-view"/);
const labHtml=fs.readFileSync(require.resolve('../a2a.html'),'utf8');
assert.match(labHtml,/href="https:\/\/box\.boodle\.ai\/a\/@A2ACommerceLabGuide" data-fieldwork-open-guide/);
assert.equal(E.tutorialURL(base),base+'start.html');
assert.equal(E.tutorialURL(base+'?demo=home'),null);
assert.equal(R.destination(base),base+'start.html');
assert.equal(R.destination(base+'index.html'),base+'start.html');
for(const [query,alias] of [['','FieldworkFirstSteps'],['?demo=home','FieldworkPortfolioGuide'],['?demo=budget','CommunityBudgetCoach'],['?demo=history','PuebloHistoryDetective'],['?demo=hearing','EastbankHearingGuide'],['?demo=quakes&case=alaska1964&step=reach','EarthquakeTsunamiGuide']]) {
  const c=R.combo(base+query);assert.equal(c.companion,alias);assert.ok(c.url.startsWith(base));
}
const back=base+'start.html?step=return&pass=abcdefgh&badge=lantern&topic=budget';
assert.equal(R.destination(back),back+'&here=1');
const page={id:2,windowId:1,splitViewId:4,url:back};
const chat={id:1,windowId:1,splitViewId:4,url:'https://box.boodle.ai/c/practice'};
assert.equal(R.paired(chat,[chat,page]).tabId,2);
assert.equal(R.pairedChat(page,[chat,page]).tabId,1);
assert.equal(R.combo('https://denson.github.io/colorado-weed-field-guide/companion/').companion,'ColoradoWeedGuide');
for(const url of ['https://denson.github.io/fieldwork-other/','https://denson.github.io/other/','https://evil.example/fieldwork/','https://user:pass@denson.github.io/fieldwork/','https://denson.github.io/fieldwork/%2fstart.html','https://denson.github.io/fieldwork/%2estart.html']){assert.equal(R.destination(url),null);assert.equal(R.isActivity(url),false);}
assert.equal(R.destination(base+'lessons/budget.md'),null);
assert.equal(R.destination(base+'assets/history-casebook.png'),null);
assert.equal(R.destination(base+'device-support.html'),base+'device-support.html');
assert.equal(R.combo(base+'device-support.html').companion,'DeviceSupportWorkspace');
assert.equal(R.combo(base+'a2a.html').companion,'A2ACommerceLabGuide');
assert.equal(R.combo(base+'tsunami.html?case=alaska1964&step=reach').companion,'EarthquakeTsunamiGuide');
assert.equal(R.destination(base+'tsunami.html?case=alaska1964&step=reach'),base+'tsunami.html?case=alaska1964&step=reach');
const tsunamiPage={id:5,windowId:1,splitViewId:6,url:base+'tsunami.html?case=alaska1964&step=reach'};
const blankTsunamiPane={id:6,windowId:1,splitViewId:6,url:'chrome://tab-search.top-chrome/split_new_tab_page.html'};
assert.equal(R.pairedGuide(tsunamiPage,[tsunamiPage,blankTsunamiPane]).tabId,6);
assert.equal(R.profileAlias('https://box.boodle.ai/a/@A2ACommerceLabGuide'),'A2ACommerceLabGuide');
assert.equal(R.profileAlias('https://box.boodle.ai/a/@DeviceSupportWorkspace'),'DeviceSupportWorkspace');
const supportPage={id:3,windowId:1,splitViewId:5,url:base+'device-support.html'};
const emptyGuidePane={id:4,windowId:1,splitViewId:5,url:'chrome://tab-search.top-chrome/split_new_tab_page.html'};
assert.equal(R.pairedGuide(supportPage,[supportPage,emptyGuidePane]).tabId,4);
assert.equal(R.pairedGuide(supportPage,[supportPage,{...emptyGuidePane,url:'https://box.boodle.ai/a/@DeviceSupportWorkspace'}]).tabId,4);
assert.equal(R.pairedGuide(supportPage,[supportPage,{...emptyGuidePane,url:'https://box.boodle.ai/c/support'}]).tabId,4);
assert.equal(R.pairedGuide(supportPage,[supportPage,{...emptyGuidePane,url:'https://example.com/'}]).reason,'different-site');
assert.equal(R.pairedGuide(supportPage,[supportPage,{...emptyGuidePane,splitViewId:6}]).reason,'no-unique-pair');
assert.equal(R.destination(base+'device-support.html/other'),null);
assert.equal(R.destination('https://evil.example/fieldwork/device-support.html'),null);
const m=JSON.parse(fs.readFileSync(require.resolve('../../chrome-extension/manifest.json'),'utf8'));
assert.ok(m.content_scripts.some(s=>s.matches.includes(base+'*')));
assert.deepEqual(m.permissions,['storage','tabs']);
console.log('Public Pages routes, paired notes, known companions and project boundaries passed.');
