(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.FieldworkBusinessCore=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  const version='2026-09-09.1';
  const steps=['idea','customer','offer','numbers','test','review'];
  const labels={name:'Working business name',idea:'What you will offer',customer:'First customer group',problem:'Problem worth solving',evidence:'What you know and how you know it',offer:'One thing a customer can buy',alternative:'What customers do today / why choose you',reach:'How you will reach the first customers',delivery:'How you will deliver the work',resources:'People, equipment and requirements to check',unit:'One sale means',price:'Price per sale',variable:'Cost per sale',fixed:'Monthly fixed costs',sales:'Expected sales per month',capacity:'Sales you could deliver per month',startup:'One-time startup costs',test:'First real-world test',success:'What result would justify another step',next:'Next action and when',question:'Question for an adviser'};
  const textKeys=Object.keys(labels).filter(k=>!['price','variable','fixed','sales','capacity','startup'].includes(k));
  const numberKeys=['price','variable','fixed','sales','capacity','startup'];
  const example={name:'Mesa Yard Care — fictional example',idea:'A small yard-care service offering scheduled cleanup and weeding.',customer:'Older homeowners in one Pueblo neighborhood who want help keeping a small yard manageable.',problem:'Routine yard work has become difficult, but a large landscaping contract feels unnecessary.',evidence:'Practice assumption only. No customer interviews or local demand research have been completed.',offer:'One two-hour yard-care visit, excluding tree work and pesticide application.',alternative:'Do it themselves, ask family, or hire a larger crew. We would test whether a small scheduled visit is more useful.',reach:'Ask a neighborhood organization whether we can talk with five interested homeowners.',delivery:'One owner provides scheduled visits in a small service area, using a checklist agreed with each customer.',resources:'Check equipment, transport, insurance, local requirements and a safe scope of work before offering a paid visit.',unit:'one two-hour visit',price:'90',variable:'20',fixed:'700',sales:'20',capacity:'30',startup:'1800',test:'Talk with five potential customers about their last experience arranging yard help. If there is interest, offer a clearly scoped paid pilot after requirements are checked.',success:'Two people request a follow-up about a paid visit. Treat this as an early signal, not proof of a market.',next:'Draft five interview questions and arrange the first conversation this week.',question:'What am I missing in the costs and practical requirements for a one-person service?'};
  function cleanPlan(raw={}){const p={};for(const k of Object.keys(labels))p[k]=typeof raw[k]==='string'?raw[k].slice(0,numberKeys.includes(k)?18:500):'';return p;}
  function amount(value){if(typeof value!=='string'||value.trim()===''||!/^\d+(\.\d{1,2})?$/.test(value.trim()))return null;const n=Number(value);return Number.isFinite(n)&&n<=1000000?n:null;}
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
  function calculate(plan){
    const p=cleanPlan(plan),n=Object.fromEntries(numberKeys.map(k=>[k,amount(p[k])]));
    const invalid=numberKeys.filter(k=>p[k].trim()!==''&&n[k]===null);
    for(const k of ['sales','capacity'])if(n[k]!==null&&!Number.isInteger(n[k]))invalid.push(k);
    const required=['price','variable','fixed','sales'];
    if(invalid.length||required.some(k=>n[k]===null))return {ready:false,invalid,missing:required.filter(k=>n[k]===null)};
    // Money is calculated in cents. Round up break-even to a whole sale.
    const price=Math.round(n.price*100),variable=Math.round(n.variable*100),fixed=Math.round(n.fixed*100),margin=price-variable;
    const revenue=price*n.sales/100,totalVariable=variable*n.sales/100;
    const breakEven=margin>0?Math.ceil(fixed/margin):null;
    const result=(revenue-totalVariable)-fixed/100;
    const lowerSales=Math.floor(n.sales*0.75),lowerResult=(margin*lowerSales-fixed)/100;
    return {ready:true,...n,revenue,totalVariable,margin:margin/100,result,breakEven,lowerSales,lowerResult,overCapacity:n.capacity!==null&&n.sales>n.capacity,breakEvenOverCapacity:n.capacity!==null&&breakEven!==null&&breakEven>n.capacity};
  }
  function numericSummary(plan){const r=calculate(plan);if(!r.ready)return 'Numbers are incomplete or invalid; no result has been calculated.';return `Monthly revenue: ${money(r.revenue)}\nCosts that vary with sales: ${money(r.totalVariable)}\nMonthly fixed costs: ${money(r.fixed)}\nOperating remainder: ${money(r.result)}\nContribution per sale: ${money(r.margin)}\nOperating break-even: ${r.breakEven===null?'Not attainable with a non-positive contribution per sale':r.breakEven+' sales per month'}\nAt 25% fewer sales (rounded down to ${r.lowerSales}): ${money(r.lowerResult)} operating remainder\n${r.overCapacity?'Expected sales exceed stated capacity.\n':''}${r.breakEvenOverCapacity?'Operating break-even exceeds stated capacity.\n':''}Excludes owner pay unless entered in costs, income taxes, debt payments and recovery of one-time startup spending. This is an estimate, not a cash-flow forecast.`;}
  function planText(plan){const p=cleanPlan(plan);return `FIELDWORK — BUSINESS PLAN FIRST DRAFT\nVersion ${version}\nWorking assumptions for discussion; not a financing application.\n\n${Object.entries(labels).map(([k,label])=>`${label}: ${p[k].trim()||'Not filled in yet'}`).join('\n\n')}\n\nSIMPLE MONTHLY MODEL\n${numericSummary(p)}\n\nNEXT PLANNING WORK\nValidate demand, check complete costs and local requirements, and build a cash-flow forecast with an adviser.\n\nPlanning reference: https://www.sba.gov/business-guide/plan-your-business/write-your-business-plan\nActivity: https://denson.github.io/fieldwork/?demo=business`;
  }
  function feedbackText(plan,feedback={},includePlan=false){const safe=k=>typeof feedback[k]==='string'?feedback[k].trim().slice(0,1500):'';return `FIELDWORK — BUSINESS PLAN DEMO FEEDBACK\nVersion ${version}\nActivity: https://denson.github.io/fieldwork/?demo=business\n\nReviewer (optional): ${safe('name')||'Not supplied'}\nWould I use this with a new business owner? ${safe('use')||'Not answered'}\n\nWhat helped?\n${safe('helped')||'Not answered'}\n\nWhere did I get stuck or confused?\n${safe('confused')||'Not answered'}\n\nWhat would I change or add?\n${safe('change')||'Not answered'}\n\n${includePlan?'INCLUDED FIRST DRAFT\n\n'+planText(plan):'Business-plan answers are not included in this feedback package.'}`;}
  function emailDraft(address,body){if(typeof address!=='string'||! /^[a-z0-9.!$'*+_~-]+@[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?\.[a-z]{2,}$/i.test(address))return null;const subject='Feedback: Fieldwork business-plan demo';const full='mailto:'+address+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);if(full.length<=1800)return {href:full,attach:false};const brief='I tried the Fieldwork business-plan demo. My feedback is in the text file I will attach.\n\nPlease attach the downloaded fieldwork-business-feedback.txt before sending.';return {href:'mailto:'+address+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(brief),attach:true};}
  function chatNote(plan,step){const p=cleanPlan(plan);const keys={idea:['name','idea'],customer:['customer','problem','evidence'],offer:['offer','alternative','reach','delivery','resources'],numbers:['unit','price','variable','fixed','sales','capacity','startup'],test:['test','success','next','question'],review:['name','idea','customer','offer','next','question']}[step]||['idea'];return `FIELDWORK BUSINESS PLAN — ${steps.includes(step)?step:'idea'}\nThese are my draft ideas and assumptions, not verified facts.\n\n${keys.map(k=>`${labels[k]}: ${p[k]||'Not filled in yet'}`).join('\n\n')}\n${step==='numbers'?'\n'+numericSummary(p)+'\n':''}\nHelp me improve this step. Ask one useful question and wait for my answer.\nMy activity: https://denson.github.io/fieldwork/?demo=business&step=${steps.includes(step)?step:'idea'}`.slice(0,3700);}
  return {version,steps,labels,example,cleanPlan,calculate,money,numericSummary,planText,feedbackText,emailDraft,chatNote};
});
