window.FIELDWORK_CASES = [
  {
    key: 'flood-camp', number: '01', short: 'Shelter', year: '1921', id: '2017679286',
    title: 'A general view of the camp, showing the extent of the tents. Pueblo, Colorado flood',
    date: 'June 4, 1921 (catalog date)', image: 'assets/pueblo-flood-camp-1921.jpg',
    credit: 'American National Red Cross photograph collection, Library of Congress.',
    creator: 'No individual photographer named. The caption card identifies the source as Southwestern Division.',
    catalog: 'https://www.loc.gov/item/2017679286/',
    download: 'https://tile.loc.gov/storage-services/service/pnp/anrc/14100/14136v.jpg',
    rights: 'No known restrictions on publication.',
    notes: 'Title, date, and notes come from the Red Cross caption card. Classified as Disaster Relief. July 1921 is a separate date received, not the catalog’s created/published date.',
    prompt: 'How might shelter have been organized after the flood? Look for details before building an explanation.',
    limit: 'This photograph alone cannot establish camp capacity, residents’ identities, length of stay, or whether everyone had adequate shelter.',
    quiz: ['The record identifies a tent camp connected with the Pueblo flood.', 'Every Pueblo resident lived in this camp.', 'The photograph proves that relief efforts met everyone’s needs.'],
    correct: 0, explanation: 'The title and catalog support the first claim. Population coverage and the adequacy of relief would need other records.'
  },
  {
    key: 'flood-mess-hall', number: '02', short: 'Food & relief', year: '1921', id: '2017679288',
    title: 'Interior of the mess hall. Pueblo, Colo. flood',
    date: 'June 4, 1921 (catalog date)', image: 'assets/pueblo-flood-mess-hall-1921.jpg',
    credit: 'American National Red Cross photograph collection, Library of Congress.',
    creator: 'No individual photographer named. The caption card identifies the source as Southwest Division.',
    catalog: 'https://www.loc.gov/item/2017679288/',
    download: 'https://tile.loc.gov/storage-services/service/pnp/anrc/14100/14138v.jpg',
    rights: 'No known restrictions on publication.',
    notes: 'Title, date, and notes come from the Red Cross caption card. Classified as Disaster Relief.',
    prompt: 'What would it take to operate this space? Separate the objects you see from the roles you infer.',
    limit: 'The record does not establish how many people were fed, how often meals were served, or whether everyone’s needs were met.',
    quiz: ['The city government provided no assistance.', 'The catalog identifies a mess-hall interior connected with the flood.', 'This meal schedule continued for a full year.'],
    correct: 1, explanation: 'The catalog names the setting. It does not establish a meal schedule or what other organizations and government agencies did.'
  },
  {
    key: 'union-avenue', number: '03', short: 'A later streetscape', year: '2015', id: '2015632345',
    title: 'Storefronts in the Union Avenue Commercial District in Pueblo, Colorado',
    date: 'May 24, 2015 (photograph date)', image: 'assets/pueblo-union-avenue-2015.jpg',
    credit: 'Gates Frontiers Fund Colorado Collection within the Carol M. Highsmith Archive, Library of Congress, Prints and Photographs Division.',
    creator: 'Carol M. Highsmith, photographer.', catalog: 'https://www.loc.gov/item/2015632345/',
    download: 'https://tile.loc.gov/image-services/iiif/service:pnp:highsm:32300:32330/full/pct:25/0/default.jpg',
    rights: 'No known restrictions on publication.',
    notes: 'Title, date, and keywords are based on information supplied by the photographer. Gift of the Gates Frontiers Fund, 2015.',
    prompt: 'What changes when a photographer documents a streetscape instead of disaster relief? Look at the subjects and framing.',
    limit: 'This is a 2015 comparison, not a present-day view or a matched before-and-after photograph. It does not establish which buildings survived the 1921 flood.',
    quiz: ['The buildings shown were all constructed in 2015.', 'This is a current view of Union Avenue.', 'The record identifies a photograph made on May 24, 2015.'],
    correct: 2, explanation: 'A photograph’s date is not the construction date of the buildings it depicts. Nor is a 2015 photograph a current street view.'
  },
  {
    key: 'flood-damage', number: '04', short: 'Flood damage', year: '1921', id: '2017679238',
    title: 'View showing the general devastation wrought by the flood to the industrial and business districts Pueblo, Col.',
    date: 'June 3–4, 1921 (catalog: date received)', image: 'assets/pueblo-flood-damage-1921.jpg',
    alt: 'Black-and-white elevated view across broad floodwater, buildings, industrial chimneys, and rail lines, with a large dark shadow in the foreground.',
    credit: 'American National Red Cross photograph collection, Library of Congress.',
    creator: 'The caption card or negative sleeve identifies the photographer or source as Standley.',
    catalog: 'https://www.loc.gov/item/2017679238/',
    download: 'https://tile.loc.gov/storage-services/service/pnp/anrc/14000/14087v.jpg',
    rights: 'No known restrictions on publication.',
    notes: 'Title, date, and notes come from the Red Cross caption card. The catalog explicitly labels June 3–4, 1921 as date received. Classified as Disaster Relief.',
    prompt: 'What details suggest disruption to the city? Compare this wide view with the camp or mess hall before explaining how people responded.',
    limit: 'The catalog date is a date received, not a verified exposure date. One view cannot establish total losses, water depth, the fate of individual buildings, or everyone’s experience of the flood.',
    quiz: ['The photograph proves the exact financial cost of the flood.', 'The catalog identifies flood damage in Pueblo’s industrial and business districts.', 'The catalog verifies the exact moment this photograph was taken.'],
    correct: 1, explanation: 'The title supports the location and subject. The date is explicitly labeled date received; loss estimates and exposure time would require other evidence.'
  },
  {
    key: 'relief-shoes', number: '05', short: 'Clothing & supplies', year: '1921', id: '2017679283',
    title: 'A few of the shoes that were sent into the south side Red Cross Relief Station for distribution among the flood sufferers. Pueblo Colorado flood',
    date: 'June 4, 1921 (catalog date)', image: 'assets/pueblo-flood-relief-shoes-1921.jpg',
    alt: 'Black-and-white room interior with many shoes arranged on rows of desks and a person standing near a chalkboard.',
    credit: 'American National Red Cross photograph collection, Library of Congress.',
    creator: 'No individual photographer named. The caption card identifies the source as Southwest Division.',
    catalog: 'https://www.loc.gov/item/2017679283/',
    download: 'https://tile.loc.gov/storage-services/service/pnp/anrc/14100/14133v.jpg',
    rights: 'No known restrictions on publication.',
    notes: 'Title, date, and notes come from the Red Cross caption card. Classified as Disaster Relief. July 1921 is a separate date received.',
    prompt: 'What needs do these supplies suggest beyond shelter and food? Describe what you see, then ask what a distribution record could tell you.',
    limit: 'The title identifies shoes intended for distribution. The photograph does not establish who received them, the person’s role, whether distribution is happening, or whether everyone received a suitable pair.',
    quiz: ['The title identifies shoes sent to a relief station for distribution.', 'Every flood survivor received a new pair of shoes.', 'The person shown is identified as the relief-station director.'],
    correct: 0, explanation: 'The title establishes the intended purpose of the shoes. It does not establish coverage, recipients, condition of every pair, or the identity and role of the person shown.'
  },
  {
    key: 'steel-mill', number: '06', short: 'Industrial Pueblo', year: '2015', id: '2015632683',
    title: 'Long idle parts of the giant Colorado Fuel and Iron steel mill, founded in 1881, in Pueblo, Colorado',
    date: 'May 22, 2015 (photograph date)', image: 'assets/pueblo-steel-mill-2015.jpg',
    alt: 'Color photograph of brick industrial buildings, tall cylindrical structures and chimneys, with railway tracks in the foreground beneath a blue, cloud-filled sky.',
    credit: 'Gates Frontiers Fund Colorado Collection within the Carol M. Highsmith Archive, Library of Congress, Prints and Photographs Division.',
    creator: 'Carol M. Highsmith, photographer.',
    catalog: 'https://www.loc.gov/item/2015632683/',
    download: 'https://tile.loc.gov/image-services/iiif/service:pnp:highsm:32600:32668/full/pct:25/0/default.jpg',
    rights: 'No known restrictions on publication.',
    notes: 'Title, date, and keywords are based on information supplied by the photographer. Gift of the Gates Frontiers Fund, 2015.',
    prompt: 'Compare this industrial view with Union Avenue, photographed two days later. What does each image emphasize, and whose experiences are missing?',
    limit: 'The title describes parts of the mill in 2015. It does not establish that the entire plant was closed, that the flood caused this condition, or what the site looks like today.',
    quiz: ['The 1921 flood caused the condition shown in 2015.', 'The entire steel plant was closed when this was photographed.', 'The record identifies a 2015 photograph of parts of the Colorado Fuel and Iron mill.'],
    correct: 2, explanation: 'The catalog identifies the subject and photograph date. A causal link to the flood and a claim about the entire plant go beyond this record.'
  }
];
