(function(){
  'use strict';
  const J=window.FieldworkJourneyCore,$=id=>document.getElementById(id),host=$('tsunami-journey');
  if(!host||!J)return;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const params=new URLSearchParams(location.search),prefix='fieldwork:'+J.VERSION+':';
  let storageOK=true;
  function read(key){try{return localStorage.getItem(prefix+key);}catch{storageOK=false;return null;}}
  function savedFor(key){try{return JSON.parse(read(key));}catch{return null;}}
  const requested=params.get('demo')==='quakes'&&Object.hasOwn(J.cases,params.get('case'))?params.get('case'):read('last-case');
  const initialCase=Object.hasOwn(J.cases,requested)?requested:'alaska1964';
  let state=J.entry(savedFor(initialCase)||{...J.blank(),case:initialCase},params);
  let restored=Boolean(state.updated);
  const hintOpen=new Set();
  const caseLabel=()=>J.cases[state.case].title;
  function save(){state.updated=new Date().toISOString();try{localStorage.setItem(prefix+state.case,JSON.stringify(state));localStorage.setItem(prefix+'last-case',state.case);storageOK=true;}catch{storageOK=false;}
    const status=$('journey-save');if(status)status.textContent=storageOK?'Saved in this browser.':'Browser saving is unavailable. Copy a checkpoint before leaving.';
  }
  function address(){if(new URLSearchParams(location.search).get('demo')!=='quakes')return;try{const u=new URL(location.href);u.searchParams.set('case',state.case);u.searchParams.set('step',state.step);u.hash='';history.replaceState(null,'',u.href);}catch{}}
  function visit(){if(state.step!=='review'&&!state.visited.includes(state.step))state.visited.push(state.step);}
  function navigate(step){if(![...J.steps.map(s=>s[0]),'review'].includes(step))return;state.step=step;visit();save();address();render();$('journey-heading').focus();$('tsunami-journey').scrollIntoView({block:'start',behavior:'instant'});}
  const link=(url,label)=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`;
  const note=(id,label,placeholder='One or two sentences is enough.')=>`<label for="journey-text-${id}">${esc(label)}</label><textarea id="journey-text-${id}" data-jtext="${id}" rows="3" maxlength="1200" placeholder="${esc(placeholder)}">${esc(state.text[id]||'')}</textarea>`;
  const hint=(id,text)=>`<button class="j-text-button" data-jhint="${id}" aria-expanded="${hintOpen.has(id)}">${hintOpen.has(id)?'Hide hint':'Show a hint'}</button>${hintOpen.has(id)?`<p class="j-hint">${esc(text)}</p>`:''}`;
  const reveal=(id,label,text)=>`<button class="button secondary" data-jreveal="${id}" aria-expanded="${state.reveals.includes(id)}">${state.reveals.includes(id)?'Hide explanation':esc(label)}</button>${state.reveals.includes(id)?`<div class="j-feedback">${text}</div>`:''}`;
  function figure(image,alt,credit,source){return `<figure class="j-source"><a href="${esc(image)}" target="_blank" rel="noopener noreferrer" aria-label="Open image at full size"><img src="${esc(image)}" alt="${esc(alt)}" decoding="async"></a><figcaption>${esc(credit)} · ${link(source,'Source')}<br>Click the image to inspect it at full size.</figcaption></figure>`;}
  function check(id){const c=J.checks[id],r=J.result(state,id);return `<fieldset class="j-check"><legend>${esc(c.prompt)}</legend><div class="j-options">${c.options.map(([v,label])=>`<button id="j-choice-${id}-${v}" data-jcheck="${id}" data-value="${v}" aria-pressed="${state.choices[id]===v}"><span class="j-option-dot" aria-hidden="true">${state.choices[id]===v?'●':'○'}</span>${esc(label)}</button>`).join('')}</div>${hint(id,c.hint)}<div class="j-feedback ${r&&!r.correct?'j-reconsider':''}" aria-live="polite" ${r?'':'hidden'}>${r?`<b>${r.correct?'That fits the evidence.':'Take another look.'}</b> ${esc(r.feedback)}`:''}</div></fieldset>`;}
  function system(removed=''){
    return `<div class="j-system" aria-label="Seismic information and ocean observations converge on NOAA warning centers; alerts reach communities that need ways to act."><div class="j-sensor-row"><div><span>Ground motion</span><b>USGS + seismic partners</b><p>Location, depth, magnitude</p></div><div class="${removed==='ocean'?'j-muted-function':''}"><span>Water response</span><b>NOAA + ocean partners</b><p>${removed==='ocean'?'Ocean observations removed':'DART + coastal gauges'}</p></div></div><div class="j-converge" aria-hidden="true">↘ &nbsp; &nbsp; ↙</div><div class="j-center"><span>Evidence + forecast models</span><b>NOAA tsunami warning centers</b><p>Assess the hazard. Issue and update alerts.</p></div><p class="j-timing">An initial alert can use seismic information and models before ocean confirmation.</p><div class="j-down ${removed==='message'?'j-muted-function':''}">${removed==='message'?'× Warning communication removed':'↓ Alerts reach emergency managers and the public'}</div><div class="j-community ${removed==='access'?'j-muted-function':''}"><b>Communities able to act</b><p>${removed==='access'?'Accessible routes and assistance removed':'Clear messages · preparation · accessible evacuation routes'}</p></div></div>`;
  }
  function seafloorSketch(){
    const survey=state.survey,points=J.surveyPoints(survey),x=p=>36+p*5.28,y=d=>27+d*0.039;
    const path=values=>values.map(([p,d],i)=>`${i?'L':'M'} ${x(p).toFixed(1)} ${y(d).toFixed(1)}`).join(' ');
    const estimate=Array.from({length:21},(_,i)=>[i*5,J.surveyEstimate(survey,i*5)]);
    const actual=Array.from({length:21},(_,i)=>[i*5,J.surveyDepth(i*5)]);
    const selected=survey.position,remaining=J.surveyBudget-survey.probes.length,already=points.some(([p])=>p===selected);
    return `<section class="j-survey" aria-labelledby="j-survey-title">
      <p class="eyebrow">Optional investigation · fictional seafloor</p><h3 id="j-survey-title">What could a sparse seafloor map miss?</h3>
      <p>A research boat can measure water depth at one point, but the bottom between readings remains unknown. This 100 km ocean transect begins with only three soundings. The dashed line <strong>connects the measurements</strong>; it is an estimate, not a measurement of everything between them. You can choose four more places to measure. Where would you look before trusting the map?</p>
      <div class="j-survey-grid"><div class="j-survey-map"><svg viewBox="0 0 600 250" role="img" aria-label="Fictional ocean cross-section. Dark dots mark measured depths; the dashed line estimates unmeasured seafloor.${survey.revealed?' An orange line shows the revealed hidden profile.':''}"><rect x="36" y="27" width="528" height="195" fill="#dceef2"/><path d="M36 27H564" stroke="#416b78" stroke-width="2"/><path d="M36 222H564" stroke="#899da0" stroke-width="1"/><path d="${path(estimate)}" fill="none" stroke="#416b78" stroke-width="3" stroke-dasharray="8 5"/>${survey.revealed?`<path d="${path(actual)}" fill="none" stroke="#b45324" stroke-width="4"/>`:''}${points.map(([p,d])=>`<circle cx="${x(p)}" cy="${y(d)}" r="5" fill="#123b50"/>`).join('')}<path class="j-survey-marker" d="M${x(selected)} 27V222" stroke="#1c746c" stroke-width="2" stroke-dasharray="4 4"/><text x="36" y="18">surface</text><text x="36" y="244">0 km</text><text x="518" y="244">100 km</text></svg><p class="j-survey-key"><span><i class="j-key-dot"></i> Sounding</span><span><i class="j-key-estimate"></i> Estimated bottom</span>${survey.revealed?'<span><i class="j-key-actual"></i> Revealed bottom</span>':''}</p><p class="j-small">Depth increases downward. The shape is exaggerated vertically so a shallow feature is easier to see.</p></div>
      <div class="j-survey-controls"><label for="j-survey-position">Move the survey boat: <output id="j-survey-position-value" for="j-survey-position">${selected} km</output></label><input id="j-survey-position" data-jsurvey-position type="range" min="0" max="100" step="5" value="${selected}" ${survey.revealed?'disabled':''}><button class="button primary" data-jsurvey-sound ${remaining&& !already && !survey.revealed?'':'disabled'}>Take a sounding</button><p id="j-survey-status" aria-live="polite">${survey.revealed?'Survey revealed. Reset to investigate again.':remaining?`${remaining} sounding${remaining===1?'':'s'} left. ${already?'This location has already been measured.':'Choose a location, then measure.'}`:'All four extra soundings used. Make a prediction and reveal the seafloor.'}</p><button class="j-text-button" data-jsurvey-reset>Reset this survey</button></div></div>
      <div class="j-survey-readings"><h4>Measurements so far</h4><p>${points.map(([p,d])=>`<span>${p} km <b>${d.toLocaleString()} m</b>${J.surveySeeds.includes(p)?' · starter':''}</span>`).join('')}</p></div>
      <div class="j-survey-predict"><h4>Before the reveal, what do you think?</h4><p>Use your four soundings first. Could the mostly deep readings be hiding a shallow feature between them? You may be uncertain—that is a useful answer when coverage is sparse.</p><div role="group" aria-label="Choose a prediction">${Object.entries(J.surveyPredictions).map(([id,label])=>`<button data-jsurvey-predict="${id}" aria-pressed="${survey.prediction===id}" ${survey.revealed||remaining?'disabled':''}>${esc(label)}</button>`).join('')}</div><button class="button secondary" data-jsurvey-reveal ${survey.prediction&&!remaining?'':'disabled'}>${survey.revealed?'Seafloor revealed':'Reveal the hidden seafloor'}</button></div>
      ${survey.revealed?`<div class="j-survey-result" aria-live="polite"><h4>Now compare the lines.</h4><p>The fictional profile contains a narrow ridge near 65 km, rising to 800 m below the surface. ${survey.probes.some(p=>p>=55&&p<=75)?'One or more of your extra soundings caught the shallow area.':'Your extra soundings missed the shallowest area—an honest result of limited sampling.'} The dashed map joined known points but could not show a feature it never measured.</p><p>A shallower stretch can slow a long tsunami wave. Detailed bathymetry helps models estimate where waves travel, but this drawing cannot calculate a real arrival time or tell anyone when to evacuate.</p></div>`:''}
      ${note('surveyInsight','What did your measurements establish, and what remained uncertain?','For example: I measured near… I would check…')}
      <button class="button secondary" data-jexport="survey" ${J.surveyReady(survey)?'':'disabled'}>Discuss my survey with the guide ↗</button><p class="j-small">Review the note before sharing. This is a fictional transect, not the seafloor of ${esc(caseLabel())} or an alert. ${link('https://www.ncei.noaa.gov/noaa-provides-back-school-resources','NOAA: Bathymetry in Action')} · ${link('https://www.ncei.noaa.gov/news/digital-elevation-models-and-tsunamis','NOAA: seafloor data and tsunamis')}</p>
    </section>`;
  }
  function reach(){const c=J.cases[state.case];return `<div class="j-columns"><div>${figure(c.image,c.alt,c.credit,c.imageSource)}<div class="j-evidence"><b>${esc(c.toll)}</b><p>${esc(c.caution)}</p>${link(c.source,'Historical source')}</div></div><div class="j-work"><p class="j-lead">${esc(c.intro)}</p>${note('reach',c.prompt,'An initial idea is welcome—even if you are unsure.')}${hint('reach','Think about the distance a wave can travel, rather than where people felt the ground shake.')}${reveal('reach','See how the evidence connects',`<p>${esc(c.explanation)}</p>`)}<div class="j-media"><h3>Look for the reach of the waves.</h3>${c.animation?`<p>${link(c.animation,`Open NOAA’s ${c.title} animation`)}</p>`:`<p>${link('assets/tsunami/noaa-tsunami-formation.jpg','Open the tsunami-formation diagram')}</p>`}<p>Look for where the waves travel beyond their source. A model illustrates the process; it is not a live warning.</p><button class="j-text-button" data-jaction="returned">${state.mediaReturned?'Return recorded':'I am back from the image or animation'}</button><p class="j-small">Take your time. If the media is unavailable, use the source image and explanation above.</p>${note('observation','What is one thing you noticed?','Describe the spread or reach. You can also describe the source image.')}</div></div></div>${seafloorSketch()}`;}
  function instruments(){return `<p class="j-lead">An earthquake is a clue. Understanding the water and reaching people take additional kinds of work.</p><div class="j-columns"><div>${system()}<p class="j-small">A simplified relationship diagram—not a mandatory waiting sequence. ${link('https://www.usgs.gov/faqs/there-a-system-warn-populations-imminent-occurrence-a-tsunami','USGS: the partnership')}</p></div><div><div class="j-worked"><span class="eyebrow">One example, explained</span><h3>Ground shaking → earthquake information</h3><p>Seismometers record ground motion. USGS and its partners use those records to estimate where the earthquake happened, its depth, and magnitude. That does not by itself establish that a tsunami formed.</p></div>${check('water')}${check('alerts')}${check('action')}</div></div><details class="j-details"><summary>Inspect the actual instruments</summary><div class="j-columns">${figure('assets/tsunami/pmel-dart-cutaway.jpg','NOAA DART cutaway: a pressure recorder, surface buoy, and satellite connection.','NOAA/PMEL, reproduced in Oceanography · CC BY 4.0 · historical warning-center labels','https://tos.org/oceanography/article/50-years-of-pmel-tsunami-research-and-development')}${figure('assets/tsunami/usgs-ridgecrest-installation.jpg','USGS workers installing a seismometer near Ridgecrest.','Elizabeth Cochran, USGS · 2019 · public domain · broader earthquake monitoring','https://www.usgs.gov/media/images/seismometer-installation-ridgecrest-california')}</div></details>`;}
  function missing(){const g=J.gaps[state.gap];return `<p class="j-lead">Take away one function. What information or capability disappears?</p><div class="j-function-picker" role="group" aria-label="Choose a missing function">${Object.entries(J.gaps).map(([id,v])=>`<button class="button secondary" data-jgap="${id}" aria-pressed="${id===state.gap}">${esc(v.title)}</button>`).join('')}<button class="j-text-button" data-jaction="restore-system">Restore all functions</button></div><div class="j-columns"><div>${system(state.reveals.includes('system')?'':state.gap)}<p class="j-small">This removes a whole function from a teaching diagram. A single equipment outage does not necessarily remove that function from a real network.</p></div><div class="j-work"><h3>${esc(g.title)}</h3>${note(J.gapText[state.gap],g.question)}${hint('gap-'+state.gap,g.hint)}${reveal('gap-'+state.gap,'Compare with an explanation',`<p>${esc(g.feedback)}</p>`)}<div class="j-discuss"><h3>Want to talk through your reasoning?</h3><p>Bring this answer to the guide. Your answer and historical example will accompany you into the conversation.</p><button class="button secondary" data-jexport="checkpoint">Prepare a discussion checkpoint ↗</button><p class="j-small">Optional. You can continue the whole investigation here.</p></div></div></div>`;}
  function readiness(){const job=J.jobs[state.job];return `<div class="j-columns"><div>${figure('assets/noaa-dart-buoy.png','A yellow and black NOAA tsunami-monitoring buoy floating at sea.','NOAA · photograph from the 2024 DART modernization announcement','https://www.noaa.gov/news-release/biden-harris-administration-invests-30m-to-improve-tsunami-ocean-observing-system')}<div class="j-evidence"><h3>Quiet does not mean idle.</h3><p>Power, maintenance, communication links, and trained people support the ability to respond when an event happens. Seismic networks also serve earthquake response, engineering, and hazard research.</p></div></div><div class="j-work"><label for="journey-job">Choose one part of readiness</label><select id="journey-job">${Object.entries(J.jobs).map(([id,j])=>`<option value="${id}" ${state.job===id?'selected':''}>${esc(j.title)}</option>`).join('')}</select><p class="j-job-description">${esc(job.body)}</p>${note(J.jobText[state.job],'How does this work help information become useful?')}${hint('maintenance','Name the job, what it keeps working, and who needs that information or capability.')}${reveal('maintenance','Show an example',`<p>Maintaining communication links helps measurements reach warning centers and alerts reach communities. Equipment and messages need to keep working between the rare events, not just on the day of a disaster.</p>`)}</div></div><div class="j-funding"><div><span>USGS · FY2024 appropriation</span><b>$62.645 million</b><p>ANSS monitoring and reporting, supporting broader earthquake functions.</p>${link('assets/sources/usgs-earthquake-strategy-2024-2033.pdf#page=20','Saved USGS budget source')}</div><div><span>NOAA · announced in 2024</span><b>$30 million</b><p>A DART modernization investment, not an annual operating total.</p>${link('assets/sources/noaa-dart-modernization-2024.pdf','Saved NOAA announcement')}</div></div>${check('budget')}`;}
  function explain(){const transfer=state.case==='japan2011'?J.cases.alaska1964:J.cases.japan2011;return `<div class="j-transfer"><span class="eyebrow">Try the idea in another setting</span><h3>${esc(transfer.title)}</h3><p>${esc(transfer.intro)} Use what you learned about ${esc(caseLabel())} to think about this different event.</p>${link(transfer.source,'Evidence for the new example')}</div><div class="j-columns"><div>${check('transfer')}${check('quiet')}<details class="j-details" id="journey-recall-diagram"><summary data-jhelp="recall-diagram">Show the warning-system diagram</summary>${system()}</details><div class="j-safety"><h3>A nearby event can be different.</h3><p>In a coastal hazard zone, strong or long shaking, unusual ocean movement, or a roar can be a natural warning. Protect yourself during shaking, then move as soon as safely possible to high ground or inland along evacuation routes. Do not wait for an official alert; follow local officials.</p>${link('https://www.weather.gov/safety/tsunami-during','NOAA/NWS safety guidance')}</div></div><div class="j-work"><h3>Make your own explanation.</h3><p>Keep ${esc(caseLabel())} as your main example. Connect what happened with one part of the warning system and the work needed between events.</p>${note('explanation','Why maintain these systems when most days are quiet?','Use the historical evidence, explain a connection, and identify a limit or uncertainty.')}${hint('explanation','A useful structure: “This event shows… The system contributes… Keeping it ready requires… One limit is…”')}${note('question','What question would you still like to discuss?','Costs, evidence, uncertainty, or how the system works…')}<button class="button primary full" data-jexport="final">Prepare my explanation for BoodleBox ↗</button><p class="j-small">Copy the note, open the companion, and paste it. Nothing is sent automatically.</p><div class="j-later"><h3>See what stays with you.</h3><p>Return in about a week for two short questions. This is an optional review, with no reminder or account required.</p><a id="journey-review-link" href="${esc(J.url(location.href,state,'review'))}">Bookmark this return-visit link ↗</a><button class="j-text-button" data-jstep="review">Try the return visit now</button></div></div></div>`;}
  function review(){return `<p class="j-lead">Bring the ideas back to mind before opening the hints. Your earlier answers are still saved with ${esc(caseLabel())}.</p><div class="j-columns"><div>${check('reviewRoles')}${check('reviewOcean')}</div><div class="j-work">${note('review','How would you explain the value of readiness to someone new to this lesson?')}${hint('explanation','Connect a historical consequence, one function in the system, and the work that keeps it ready.')}<button class="button primary full" data-jexport="review">Prepare my return-visit note ↗</button><button class="j-text-button" data-jstep="explain">Return to my original explanation</button></div></div>`;}
  function render(){const index=J.steps.findIndex(x=>x[0]===state.step),title=index<0?'What do you remember?':J.steps[index][1];host.innerHTML=`<div class="j-top"><div><p class="eyebrow">A guided investigation · 10–15 minutes · at your pace</p><p class="j-opening">Follow a warning from the first measurements to people who can act. Try an idea, inspect the evidence, and build an explanation.</p></div><div class="j-case"><label for="journey-case">Your historical example</label><select id="journey-case">${Object.entries(J.cases).map(([id,c])=>`<option value="${id}" ${id===state.case?'selected':''}>${esc(c.title)}</option>`).join('')}</select><small>Each example keeps its own notes.</small></div></div><nav class="j-stops" aria-label="Investigation stops">${J.steps.map(([id,label],i)=>`<button data-jstep="${id}" ${state.step===id?'aria-current="step"':''}><span>${i+1}</span><b>${esc(label)}</b><small>${state.visited.includes(id)?'Visited':'Explore'}</small></button>`).join('')}</nav><div class="j-status"><span id="journey-save" role="status">${storageOK?(restored?'Resumed your saved place.':'Saved in this browser.'):'Browser saving is unavailable. Copy a checkpoint before leaving.'}</span><button class="j-text-button" data-jaction="reset">Reset this example’s notes</button></div><section class="j-stage" aria-labelledby="journey-heading"><div class="j-stage-heading"><p class="eyebrow">${index<0?'Optional return visit':`Stop ${index+1} of 5 · about ${J.steps[index][2]}`}</p><h2 id="journey-heading" tabindex="-1">${esc(title)}</h2><p class="j-case-reminder">Your main example: ${esc(caseLabel())}</p></div>${({reach,instruments,missing,readiness,explain,review})[state.step]()}<div class="j-bottom"><button class="button secondary" data-jstep="${J.steps[index<0?4:Math.max(index-1,0)][0]}" ${index===0?'disabled':''}>← Previous stop</button><span>You can revisit any stop. Visits are not a grade.</span>${index>=0&&index<4?`<button class="button primary" data-jstep="${J.steps[index+1][0]}">Continue: ${esc(J.steps[index+1][1])} →</button>`:`<button class="button secondary" data-jexport="${state.step==='review'?'review':'final'}">Prepare my note ↗</button>`}</div></section>`;restored=false;}
  host.addEventListener('input',e=>{
    if(e.target.matches('[data-jsurvey-position]')){state.survey.position=Number(e.target.value);$('j-survey-position-value').textContent=`${state.survey.position} km`;const marker=host.querySelector('.j-survey-marker');if(marker){const px=36+state.survey.position*5.28;marker.setAttribute('d',`M${px} 27V222`);}const measured=J.surveyPoints(state.survey).some(([p])=>p===state.survey.position);host.querySelector('[data-jsurvey-sound]').disabled=measured||state.survey.probes.length>=J.surveyBudget;$('j-survey-status').textContent=measured?'This location has already been measured.':`${J.surveyBudget-state.survey.probes.length} soundings left. Choose a location, then measure.`;save();return;}
    const id=e.target.dataset.jtext;if(!J.textKeys.includes(id))return;state.text[id]=e.target.value.slice(0,1200);save();
  });
  host.addEventListener('change',e=>{
    if(e.target.id==='journey-case'){
      const key=e.target.value;if(!Object.hasOwn(J.cases,key))return;save();hintOpen.clear();state=J.normalize(savedFor(key)||{...J.blank(),case:key});state.case=key;restored=Boolean(state.updated);visit();save();address();window.FieldworkJourney.onCaseChange?.(key);render();$('journey-case').focus();
    }else if(e.target.id==='journey-job'){if(Object.hasOwn(J.jobs,e.target.value)){state.job=e.target.value;save();render();$('journey-job').focus();}}
  });
  host.addEventListener('click',e=>{
    const help=e.target.closest('[data-jhelp]');if(help){if(!state.hints.includes('recall-diagram'))state.hints.push('recall-diagram');save();}
    const b=e.target.closest('button');if(!b)return;
    if(b.dataset.jstep){navigate(b.dataset.jstep);return;}
    if(b.hasAttribute('data-jsurvey-sound')){if(J.surveyProbe(state.survey,state.survey.position)){save();render();host.querySelector('[data-jsurvey-sound]')?.focus();}return;}
    if(b.dataset.jsurveyPredict&&Object.hasOwn(J.surveyPredictions,b.dataset.jsurveyPredict)&&!state.survey.revealed&&state.survey.probes.length===J.surveyBudget){state.survey.prediction=b.dataset.jsurveyPredict;save();render();host.querySelector(`[data-jsurvey-predict="${state.survey.prediction}"]`)?.focus();return;}
    if(b.hasAttribute('data-jsurvey-reveal')&&state.survey.prediction&&state.survey.probes.length===J.surveyBudget){state.survey.revealed=true;save();render();host.querySelector('[data-jsurvey-reveal]')?.focus();return;}
    if(b.hasAttribute('data-jsurvey-reset')){state.survey={...J.blank().survey};state.text.surveyInsight='';save();render();host.querySelector('[data-jsurvey-reset]')?.focus();return;}
    if(b.dataset.jcheck){if(J.choose(state,b.dataset.jcheck,b.dataset.value)){const id=b.id;save();render();$(id)?.focus();}return;}
    if(b.dataset.jhint){const id=b.dataset.jhint;if(!state.hints.includes(id))state.hints.push(id);if(hintOpen.has(id))hintOpen.delete(id);else hintOpen.add(id);save();render();host.querySelector(`[data-jhint="${id}"]`)?.focus();return;}
    if(b.dataset.jreveal){const id=b.dataset.jreveal;state.reveals=state.reveals.includes(id)?state.reveals.filter(h=>h!==id):[...state.reveals,id];if(id.startsWith('gap-')&&!state.reviewedGaps.includes(id.slice(4)))state.reviewedGaps.push(id.slice(4));save();render();host.querySelector(`[data-jreveal="${id}"]`)?.focus();return;}
    if(b.dataset.jgap&&Object.hasOwn(J.gaps,b.dataset.jgap)){state.gap=b.dataset.jgap;state.reveals=state.reveals.filter(x=>x!=='system');save();render();host.querySelector(`[data-jgap="${state.gap}"]`)?.focus();return;}
    if(b.dataset.jexport){try{save();const survey=b.dataset.jexport==='survey',content=survey?J.surveyNote(state,location.href):J.checkpoint(state,location.href,b.dataset.jexport);if(!content){$('journey-save').textContent='Make a prediction and reveal the seafloor before preparing a note.';return;}window.FieldworkBridge.openExport(survey?'Your seafloor investigation':'Your learning checkpoint',content,survey?'tsunami-seafloor-investigation.md':'tsunami-learning-checkpoint.md');}catch{$('journey-save').textContent='The note could not open. Reload the page and try again; your choices are saved in this browser.';}return;}
    if(b.dataset.jaction==='returned'){state.mediaReturned=true;save();render();$('journey-text-observation').focus();}
    if(b.dataset.jaction==='restore-system'){state.reveals.push('system');state.reveals=[...new Set(state.reveals)];save();render();}
    if(b.dataset.jaction==='reset')$('journey-reset-dialog').showModal();
  });
  $('journey-reset-confirm').addEventListener('click',()=>{const key=state.case;hintOpen.clear();state={...J.blank(),case:key};visit();save();address();$('journey-reset-dialog').close();window.FieldworkJourney.onCaseChange?.(key);render();$('journey-heading').focus();});
  $('journey-live-export').addEventListener('click',()=>$('quake-export').click());
  $('journey-how-start').addEventListener('click',()=>{$('journey-how').open=false;$('journey-heading').focus();$('tsunami-journey').scrollIntoView({block:'start',behavior:'instant'});});
  $('journey-reference').addEventListener('toggle',()=>{if($('journey-reference').open)$('journey-reference').querySelector('summary').focus();});
  if(location.hash.startsWith('#tsunami-'))$('journey-reference').open=true;
  window.FieldworkJourney={urlValues:()=>({case:state.case,step:state.step}),stateCase:()=>state.case,activate:()=>{visit();save();render();}};
  render();
})();
